#!/bin/bash

LLVM_LIBS="$(llvm-config --components)"
LLVM_LIBS=$(echo $LLVM_LIBS | sed "s/ /;/g")
LLVM_LIBS=$(echo $LLVM_LIBS | sed "s/all-targets;//g")
rm -Rf build
mkdir build
cd build
cmake .. -G Ninja -DLLVM_COMPS=$(echo $LLVM_LIBS)
